### ISSUE TITLE
C++11 example for asio spawn

### ISSUE THREAD

**Issue by absolute8511** [olk/boost-fiber#27]
I tried to use the boost::fibers::asio::spawn while using c++11, but it failed to compile and I noticed the example is missing under cpp11 directory.  Is there any example for the usage? Or is it not supported under c++11?

**Comment by erakadjiev** [comment]
Asio in the `master` branch works currently only with C++03. With relatively trivial modifications I could compile it with C++11, but it still failed during runtime. 
You can use the `develop` branch and C++14. Related details are in #29.

**Comment by olk** [comment]
please note that this project is still in development
