### ISSUE TITLE
Which branch to use currently?

### ISSUE THREAD

**Issue by erakadjiev** [olk/boost-fiber#28]
Hello Oliver,

A project I'm working on will rely on Boost Fiber and I have to start using the library in the next few days. 
Which branch is the one you recommend to use currently? The `master` is very old, so I was looking at `develop`, but there are some newer ones, too.

Thank you for the great libraries!

**Comment by olk** [comment]
Please note that boost.fiber is still in development -at the moment I'm evaluating different implementations. I preferre branch ctx_onstack_lambda at the moment.

**Comment by erakadjiev** [comment]
Thank you for the quick answer! Yes, I'm aware of the fact that the library is still in development. The project in which we have to use it is not a production project yet, so as long as a version of Boost Fiber "mostly works", it should be good for us. I'll go ahead with `ctx_onstack_lambda`, thanks!
