### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by git-patrick** [olk/boost-fiber#33]
I'm trying to get boost fiber to work on OS 10.10.4.  The first issue I had was the OS X version of Clang doesn't support thread_local for some reason.  I was considering switching fiber over to boost thread local storage instead of using thread_local, but I figured I would just try just using GCC-5.1.0 and link with stdlibc++ instead.

Building boost modular and boost fiber was successful, and building the fiber example "simple.cpp" was also successful, but it fails with segmentation faults.  Any idea what's going on?

Maybe I'll hack it to use boost thread local storage so the standard clang will work instead..

**Comment by olk** [comment]
until Apple adds support for thread_local it will not work - sorry

**Comment by Rydgel** [comment]
@olk Apple added support for thread_local since last Xcode.
It now compiles fine, but gives some segfaults deep inside boost context.

I can provide more informations if needed.

**Comment by olk** [comment]
@Rydgel yes, but report in boost.context please

**Comment by Rydgel** [comment]
This is actually this bug https://github.com/boostorg/context/issues/38
So I guess I'll just wait the next Boost release.

**Comment by olk** [comment]
@Rydgel could you verify that the code is working, please - I don't own a Mac, so I can't test it

**Comment by Rydgel** [comment]
@olk just recompiled Boost with the patch from that context issue. Everything is working now!

**Comment by olk** [comment]
@Rydgel ty
