### ISSUE TITLE
Cannot create a fiber with the tip of Boost.Context on g++ 5.2.1

### ISSUE THREAD

**Issue by tgockel** [olk/boost-fiber#69]
When trying to use Boost.Fiber with the tip of Boost.Context, I get a horrendous compilation error with basic use -- [attached](https://github.com/olk/boost-fiber/files/36112/boost.fiber-use-error.txt).

    // Event the simplest case does not work:
    boost::fibers::fiber f([] () {});

It looks like this broke with this change in Boost.Context: [43d89cb6396706871ce9378c8e3b2c63e93ffe0e - support passing argument between execution_context](https://github.com/boostorg/context/commit/43d89cb6396706871ce9378c8e3b2c63e93ffe0e).

The preceding commit works perfectly fine for me: [01660915c1330a186ed0548b436065a9fc8ec96c](https://github.com/boostorg/context/commit/01660915c1330a186ed0548b436065a9fc8ec96c)

My compiler is g++ 5.2.1.

**Comment by olk** [comment]
lambda requires argument: boost::fibers::fiber f([] (void*) {});

**Comment by olk** [comment]
Keep in mind that boost.fiber is still in development
you should use branch develop for boost.context and boost.fiber
