### ISSUE TITLE
cannot compile on master

### ISSUE THREAD

**Issue by fleonis** [olk/boost-fiber#70]
hello.
i cannot compile this code on the master branche, only on the develop branche (it was so for a few month). now on the develop branche it compiles but crashes (terminated by signal SIGSEGV (Address boundary error)). i am on db88147

``` c++
#include <iostream>
#include <boost/fiber/all.hpp>

int main(int argc, char** argv) {
        boost::fibers::fiber([](){std::cout << "hello from fiber" << std::endl;}).detach();
        boost::this_fiber::yield();

        return 0;
}
```

**Comment by olk** [comment]
please note that boost.fiber is a work-in-progress
branch main is in the moment out-dated - you need branch develop (boost.context too)

**Comment by fleonis** [comment]
ok. thank you for answer!
