### ISSUE TITLE
Included header file from Boost.Context is missing.

### ISSUE THREAD

**Issue by ClaymorePT** [olk/boost-fiber#78]
I was trying to build Fiber for Boost 1.60.0 when the following error occurred.

In file included from libs/fiber/src/algorithm.cpp:9:0:
./boost/fiber/context.hpp:20:42: fatal error: boost/context/detail/apply.hpp: No such file or directory
compilation terminated.
It seems the header "boost/context/detail/apply.hpp" was removed from boost context.
Is this an issue for fiber?

Thank you.

**Comment by olk** [comment]
boost.fiber is still in development - you need to fetch the version 1.61 (== branch develop) of boost.context. but boost/context/detail/apply.hpp is the correct path to this file - maybe you need to check your compiler include paths.

**Comment by ClaymorePT** [comment]
Oh, I didn't notice it required Boost 1.61. 
Boost 1.61 is only supposed to come out by the end of this month.

Thank you for the information.
